name: Desplegar a Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias del backend
        run: |
          cd backend
          npm install

      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: donda-library
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
